apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "checkmk.fullname" . }}
  labels:
{{ include "checkmk.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "checkmk.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "checkmk.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      initContainers:
        - command:
          - /docker-entrypoint-init.sh
          env:
          - name: CMK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "checkmk.fullname" . }}
                key: checkmk-password
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          name: checkmk-init
          volumeMounts:
          - mountPath: /omd/sites
            name: vol1
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /opt/omd/sites/cmk/tmp
            name: ramdisk
          - mountPath: /omd/sites
            name: vol1
          env:
          - name: CMK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "checkmk.fullname" . }}
                key: checkmk-password
          - name: AUTOMATION_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "checkmk.fullname" . }}
                key: checkmk-automation-secret
          - name: SNOW_MID_PASSWD
            valueFrom:
              secretKeyRef:
                name: {{ include "checkmk.fullname" . }}
                key: servicenow-password
          - name: SNOW_MID_URL
            value: {{ .Values.servicenow.url | quote }}
          - name: SNOW_MID_USER
            value: {{ .Values.servicenow.username | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 100Mi
        name: ramdisk
      - name: vol1
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "checkmk.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
